### ISSUE TITLE
To Local Format leak Date/Time adn OS language

### ISSUE THREAD

**Issue by ToLocaleFormat** [dillbyrne/random-agent-spoofer#454] opened 2016-08-20 18:15 UTC
Hello, I little speak english, sorry!

Site https://www.browserleaks.com/javascript 
Parameter "To Locale Format" detected real time, date, language OS (Ubuntu), please fix it!

Date\Time:
System Time: OK!
To Locale String: OK!
To Locale Format: BAD!!!

Screenshot: http://rgho.st/6mgZgcSSB.view

Thanks!

**Comment by stevensebaweg** [comment] 2016-08-30 20:24
Any update on this? This is definitely an easy way to detect the plugin changing the device's real timezone!

**Comment by dillbyrne** [comment] 2016-09-21 14:09
I still have not found a way to fix this but I will address it after the 0.9.5.6 release which I am going to release later today. The current way of doing script injection is not as flexible as the previous way which no longer works due to underlying browser changes.

**Comment by dillbyrne** [comment] 2016-09-21 14:26
duplicate of #417

**Closed by dillbyrne** 2016-09-21 14:26 UTC
