### ISSUE TITLE
Is there a way to disable the popups?

### ISSUE THREAD

**Issue by bceverly** [dillbyrne/random-agent-spoofer#491] opened 2016-10-29 14:06 UTC
Hi,

I love this tool, but with it set to change with every page load, the pop up showing which agent it selected gets a bit distracting.  I've scoured the UI and can't find a way to turn off the popups entirely.  Is there a way to do this?

Thanks!

**Comment by icasdri** [comment] 2016-10-29 17:40
Potential duplicate of #384, #377, #356, #387, #455, and more.

**Comment by Wannabe-Programmer** [comment] 2016-10-29 23:05
@icasdri I'm going to submit a PR soon which will include a "Disable notifications" option in the main UI. 

Any idea's where I should place it?

**Comment by icasdri** [comment] 2016-10-30 03:26
@Wannabe-Programmer Since it's not really related to the protection features of RAS, it should really go on its own tab (which currently doesn't exist). A compromise might be to put it in the `?` tab and rename that to *`<Gear Icon>`* or something of the like.

Or I guess its related to profile switching, so on second thought, where you've placed it is probably fine.

**Comment by sfzombie13** [comment] 2016-11-09 02:17
sorry about this, i thought i looked pretty good, but turns out that i was not alone at least.  i wouldn't put it anywhere, it is just fine where it is.  i would suggest letting everyone know in the documentation, however, or even disabling it by default and then nobody would look for how to turn it off.

**Comment by DrunkenSasquatch** [comment] 2016-11-09 06:23
@sfzombie13 I have always argued that when an option is really hard to find - it's essentially the same as being non-existent. Most people will not make the effort to check the wiki to find such a simple option. So it's important that developers make compensations which may not feel right to them, because thousands of people use this tool.

**Comment by sfzombie13** [comment] 2016-11-09 16:33
But as I said, if the option were set for the default action not to
notify, nobody would notice and not be looking for the option at all.
It is also a lot easier to have the check out of the box at
installation than moving things around in the interface.

-- 
Tim Sayre
Kanawha IT Security <http://kitswv.com>

**Comment by dillbyrne** [comment] 2016-11-09 16:49
I'm going to add it to the options tab for the next release, with some other UI options.

**Closed** 2016-11-16 20:14 UTC
