### ISSUE TITLE
RAS settings disappears when deactivate/activate from Firefox add-ons panel

### ISSUE THREAD

**Issue by M5oul** [dillbyrne/random-agent-spoofer#244] opened 2015-06-24 15:38 UTC
With the 0.9.5.3 version, RAS settings disappears when deactivate/activate from Firefox add-ons panel.

**Comment by dillbyrne** [comment] 2015-07-08 18:25
Duplicate of #127 

this was done due to a bug in the FF SDK. When the bug is fixed I will change the behaviour of disable.

from https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Listening_for_load_and_unload

>Due to bug [627432](https://bugzilla.mozilla.org/show_bug.cgi?id=627432), your onUnload listener will never be called with uninstall: it will only be called with disable. See in particular [comment 12](https://bugzilla.mozilla.org/show_bug.cgi?id=627432#c12) on that bug.

**Closed by dillbyrne** 2015-07-08 18:25 UTC
