### ISSUE TITLE
Disable plugin name enumeration not working

### ISSUE THREAD

**Issue by andrewcroft** [dillbyrne/random-agent-spoofer#315] opened 2015-11-17 11:15 UTC
Hi,
Thanks for a great plugin.

I have disable plugin name enumeration checked however when I go to https://panopticlick.eff.org/ it can see all of my installed plugins.

I think this is a bug.

Thanks

**Comment by RoxKilly** [comment] 2015-11-19 03:48
This is not a bug.  Firefox has backtracked and removed the ability to hide plugins because its developers feel that it breaks too many sites.  It never broke any site for me but... whatever, that's the situation.  See [details here](https://bugzilla.mozilla.org/show_bug.cgi?id=1169945).  This setting should be removed from RAS in my opinion because it has no effect any longer.

This is a duplicate of #283 .

**Comment by andrewcroft** [comment] 2015-11-19 08:47
Thanks for the reply. I agree you probably need to remove the setting or explain it only works on certain versions.

Regards

Andrew

----- Reply message -----

**Comment by dillbyrne** [comment] 2015-11-24 15:07
The preference has now been removed.

**Closed by dillbyrne** 2015-11-24 15:07 UTC

**Comment by Gitoffthelawn** [comment] 2015-11-24 20:03
FYI, I believe Mozilla is removing Firefox support for all plugins (except Flash and perhaps 1 or 2 others) in the near future.  It's quite unfortunate that Mozilla removed the ability to hide plugin enumeration, but the impact will be reduced once they disallow most plugins.  (Note that plugins and extensions are two completely different types of addons.  Extensions will be changing but will be fully supported in Firefox.)

**Comment by RoxKilly** [comment] 2016-01-09 07:47
A simple workaround (using script injection) takes only one line of javascript. See  #283
