### ISSUE TITLE
Add recent web browser

### ISSUE THREAD

**Issue by M5oul** [dillbyrne/random-agent-spoofer#239] opened 2015-06-11 19:36 UTC
It would be great if there were recent web browser profiles (Firefox 30+, Gogole Chrome 33+…etc) and a button to choose only those recent ones.
I'm asking this, cause I get messages saying my browser is old, or, web pages are not well displayed, for instance pages on GitHub.

**Comment by Mosrite** [comment] 2015-06-12 06:32
+1
I think an option to only switch between up-to-date browsers (and maybe ESR versions) would be great. Especially, because some sites cannot be used as intended with older browser versions (e.g. Google Maps).
From a UI/UX perspective, I think the best way to do this would be to leave the current options for browsers profiles as they are and add an extra checkbox, which would narrow down the browser selection (e.g. only desktop, only Windows etc.) to only up-to-date versions.

I think, this would also make sense because almost every browser updates automatically, so most people will actually use an up-to-date browser, while older versions stick out.

**Comment by dillbyrne** [comment] 2015-06-12 10:43
@M5oul you are still using the AMO version which is really out of date. I have had a new AMO version in the AMO queue for a while now but mozilla is taking weeks to approve it. The github version stays relatively up to date. The current github release 0.9.5.3 has up to firefox 37 and chrome 41 for example.

I will not be adding an option to automatically update browsers because  it does not just consist of a user agent but many properties and some of the profile properties can change between versions . I have to check each profile before adding it to ensure it is correct. 

I try to keep the profiles up to date but I could really use some assistance to keep them up to date, since the profiles come from browsers that have to be installed. If you would like to help out see https://github.com/dillbyrne/random-agent-spoofer/wiki/How-To-contribute

I'm closing this now

**Closed by dillbyrne** 2015-06-12 10:43 UTC

**Comment by M5oul** [comment] 2015-06-21 09:12
Ok, thank, I’ll install the latest GitHub version.
