### ISSUE TITLE
Issue #220 Back in FF 40.0a2 (2015-06-20)

### ISSUE THREAD

**Issue by GuardianMajor** [dillbyrne/random-agent-spoofer#242] opened 2015-06-20 17:11 UTC
Since you closed the issue without allowing me a response and allowing others to attack without a response to their claims, I have no choice but to open a new issue.

Even with the latest GitHub version, as of the above update, it is once again gone like before and does not appear or function. Let's see what other attacks the fanboys will levy this time and you will condone.

Given our history, I would have expected a better behavior and appreciation for critique, didn't realize we prefer to only hear good things and nothing else. And the use it or don't comment is the lowest tact of developer response to opposing views. Anyway, do with the information as you will.

**Comment by dillbyrne** [comment] 2015-06-20 21:03
Your last point in the previous issue was levelling accusations at me based on your opinions and you provided no information to back up your statements. 

Your original issue was dealt with and you needed to update the browser as you were still using the AMO version the issue was then closed. I informed you to uninstall the AMO version before switching to the github version.

After I closed the issue you proceeded to rant about how you did not like the the newest version and to tell me what I should do and  that I should have stood my ground when others have suggested things.

I locked the last issue because it went off topic after it was closed  and you were just ranting and telling me what I should do.  It was not exactly what I would call critique and If I only wanted to hear good things I would have deleted it, I didn’t.  It was locked because it was wasting my time by adding nothing to the discussion.

As far as I am concerned this particular conversation is over, if you don't like the direction the addon is going that is fine, you have made that clear. 

If you have an actual issue, open  a new issue with a descriptive bug report with steps to reproduce it and like other issues I will try my best to help . What you have above provides no information as to what the problem is and I can do nothing with that. 

Please see https://github.com/dillbyrne/random-agent-spoofer/wiki/Bug-reporting-guide for directions to provide a useful bug report.

I'm closing this issue now .

**Closed by dillbyrne** 2015-06-20 21:03 UTC

**Comment by GuardianMajor** [comment] 2015-07-07 18:59
As others have said and you say you can't verify, the issue after I reported above went away for a couple of nightlies but as of 41.0a2 (2015-07-07) its back.

Also with regards to my comments, you can take it how you want, that's your prerogative but a true professional doesn't throw a hissy fit and tell people to go away, tries to understand what they are saying and maybe appreciate that someone took the time to tell them how their actions might be perceived. Anyway, do with the information you are provided in good faith as you wish. If I may suggest something and its not going to be considered blasphemy, your use of jetpack might be the reason why the extension keeps disappearing with updates here and there. Just a thought, and if its not me being the antichrist for suggesting how you do things, you might want to include a way to get rid of the UA that you have in there or add custom ones. I do it on my own without issue but just saying.

As I have said a long time ago, I could just fork the good version of your extension, modify it myself and use it and that's the end of that, but as a professional, I try to support the original developer and help them modify their app to be the best it can be, rather than abandon them and create my own version, now that's respect, something you have COMPLETELY missed through our interaction.
