### ISSUE TITLE
Scren Resolution 

### ISSUE THREAD

**Issue by seli11** [dillbyrne/random-agent-spoofer#348] opened 2016-01-09 23:56 UTC
if i set scren size spofing to profile, and the profile its static lets say in chrome 42. , the resolution changes on every refresh? http://noc.to/

**Comment by dillbyrne** [comment] 2016-05-13 18:50
@seli11 It picks a compatible size from the sizes listed for the current browser profile each time. This is not a bug and will further help to change the fingerprint each time There is an issue open to make the screen size profile persist until the next profile refresh.

I'm closing this issue since there is another one open

**Closed by dillbyrne** 2016-05-13 18:50 UTC
