### ISSUE TITLE
Settings all reset when disabling/enabling addOn

### ISSUE THREAD

**Issue by B00ze64** [dillbyrne/random-agent-spoofer#310] opened 2015-10-30 02:49 UTC
Good day.

All of the "Standard Options" should default to the current state of the underlying about:config setting when RAS if first loaded or when it is disabled/enabled. Right now for example, even tho I have long ago disabled GeoLocation in user.js, that setting is UNCHECKED in RAS when RAS is first installed (or when disable/enable). The checkboxes everywhere in RAS should default to the current value.

EDIT:
Removed portion of bug which has been reported already.
Too bad I cannot change the bug title...

Thank you.
Best Regards,

**Comment by RoxKilly** [comment] 2015-10-31 14:37
Issue in the title is duplicate of #273 and #270 .

By the way, I like your advice of reading current values and reflecting them in RAS whenever the add-on UI is loaded or re-rendered.

**Comment by B00ze64** [comment] 2015-10-31 22:28
Yeah, I found the duplicate bugs **after** I created my bug, so I had to edit it and leave only the portion which is new, but I could not change the bug title :-( And actually, starting from v0.9.5.2 the "Standard" options are apparently set to their underlying values on install time - but NOT if you disable then re-enable the addOn. As you say, they should simply be read and set whenever the UI is loaded, so that if we make a change manually (using about:config) then the UI is up to date...

**Comment by dillbyrne** [comment] 2015-11-01 23:00
In order to maintain state two preferences are required for every single preference. This was the original design but was removed so the code could be cleaned up. I plan to add a toggle based system back into RAS with a cleaner implementation of the state tracking prefs.

>They should simply be read and set whenever the UI is loaded, so that if we make a change manually (using about:config) then the UI is up to date

The problem with reading current values and reflecting them in RAS whenever the add-on UI is loaded or re-rendered is that if it happens each time the panel is shown then most of it is unnecessary overhead either due to. 

There is a less resource intensive way to do this , that updates the panel in the background for the specific preference, but it adds a ton of code just so the settings can be changed in about:config instead of the using the UI directly, it would require every preference to be observed  (to use the correct mozilla speak) . As it stands only the preferences that need to be observed are. This allows the context menu and panel to work from the same code.

**Comment by B00ze64** [comment] 2015-11-02 23:37
Good day.

> In order to maintain state two preferences are required for every single preference. This was 
> the original design but was removed so the code could be cleaned up. I plan to add a toggle
> based system back into RAS with a cleaner implementation of the state tracking prefs.

Good! The biggest problem right now is when we disable the addOn (for testing something) then re-enable it, all the settings disappear :-( Less of a problem but still annoying is that I use User.js for a LOT of those "Standard" settings, and the RAS UI doesn't refresh, so I ask myself did I change it or not? I have to again look at about:config or in my User.js to make sure...

**Comment by eNTi** [comment] 2015-11-04 09:09
yeah. this is REALLY annyoing. especially for whitelisting.

**Comment by dillbyrne** [comment] 2015-11-26 20:13
duplicate of #272

**Closed by dillbyrne** 2015-11-26 20:13 UTC
Labels: duplicate
