### ISSUE TITLE
Firefox URI Leak

### ISSUE THREAD

**Issue by sueridgepipe** [dillbyrne/random-agent-spoofer#422] opened 2016-06-13 07:02 UTC
Lots of fingerprint browser info available via resource://, details here.

http://www.ghacks.net/2016/06/12/firefox-resource-leak/

Possible to stop this leak in a future RAS version?

**Comment by Wannabe-Programmer** [comment] 2016-06-14 05:29
The [No Resource URI Leak](https://addons.mozilla.org/en-US/firefox/addon/no-resource-uri-leak/) fixed the issue. 

Here is the source code used: https://addons.mozilla.org/en-US/firefox/files/browse/445831/

**Comment by beardog108** [comment] 2016-06-20 23:21
RAS should add the same fix as an option.

**Comment by dillbyrne** [comment] 2016-06-22 16:38
This has been fixed in ff48 so there is no point in adding it to RAS now as that will be out by the time I get the next version ready and it is better to have it handled in the browser itself.

![ff48](https://i.imgur.com/Fnc7z1Q.png)

**Closed by dillbyrne** 2016-06-22 16:38 UTC

**Comment by NiklasGollenstede** [comment] 2016-09-05 21:00
![leak](https://cloud.githubusercontent.com/assets/10552031/18256936/4203f25a-73bc-11e6-8373-6ede2bb53f0d.png)

Sorry to disappoint, but the test is just buggy (for a time it didn't work with 64bit FF). But as you see the problem is not solved (by Firefox itself)
