### ISSUE TITLE
Unable to move icon to a different toolbar (version 0.9.5.3)

### ISSUE THREAD

**Issue by fflintstone** [dillbyrne/random-agent-spoofer#289] opened 2015-09-07 02:13 UTC
You can't move the icon/button out of the main toolbar. If you try to move it to any vertical toolbar (see the addons:  All-in-One Sidebar or Vertical Toolbar), the icon expands way too large and messes up all the other icons in that toolbar. I, for one, do not like to leave all add-on icons in the main toolbar, so it would nice to be able to move it like I could in the old version.

**Comment by dillbyrne** [comment] 2015-09-11 18:55
Hi @fflintstone 

It works fine here for me with all in one sidebar and RAS 0.9.5.3 .

![aaa](https://cloud.githubusercontent.com/assets/2903711/9823430/07dd3718-58be-11e5-9207-971ac34c61fd.png)

It also works fine with the vertical toolbar addon RAS 0.9.5.3 .
![bbb](https://cloud.githubusercontent.com/assets/2903711/9823535/b28272e6-58be-11e5-97ce-4296c3bfbfea.png)

I am unable to reproduce it , could it be other addons you have interfering with it ?

does it also happen for https://addons.mozilla.org/en-US/firefox/addon/time-keeper/ ?

**Comment by fflintstone** [comment] 2015-11-08 05:23
I just tried Time Keeper, and that icon is distorted as well, but in a different way (stretched vertically, but not horizontally).  Now that you mention it, the problem does seem to revolve around the theme.  If I use the default theme, the icon looks normal, but if I switch to LavaFox or Blue Fox (the only other ones I've tried), the icon gets stretched.  But none of my other icons are affected the same way as the ones are for Time Keeper and Random Agent Spoofer.

**Comment by dillbyrne** [comment] 2015-11-09 14:26
I suspected it would also be distorted. This means that RAS is not the cause of this. Your theme does not seem to display sdk based addons that make use of the `ActionButton` or `ToggleButton` properly. 

As this is not a bug with RAS I'm closing this issue now.

**Closed by dillbyrne** 2015-11-09 14:26 UTC
Labels: not reproducible
