### ISSUE TITLE
Some parameters do not change immediately

### ISSUE THREAD

**Issue by Jiriss** [dillbyrne/random-agent-spoofer#208] opened 2015-05-05 20:36 UTC
When I check "Disable webRTC" -> parameter does not change immediately. It is valid until after restart of the browser. This bug is in version 0.9.5.3. However when I check for instance "Disable webGL" then it is changed immediately. I can confirm them on about:config tab.

**Comment by dillbyrne** [comment] 2015-05-05 20:42
@Jiriss it works fine here.
Did you install 0.9.5.3 fresh or did you upgrade it from a previous version. if so what was was the previous version. 

What os are you using and what version of firefox

have you tried it in a fresh profile ?.

**Comment by Jiriss** [comment] 2015-05-05 20:58
I use Firefox ESR (31.6) on Ubuntu 14.04 LTS. I did upgrade from version 0.9.5.2. I really don't like create a new profile because I would lost all my settigs etc.

**Comment by dillbyrne** [comment] 2015-05-05 20:59
Did it work for you on 0.9.5.2 ?

**Comment by Jiriss** [comment] 2015-05-05 21:02
I don't know because I didn't test it when I used the previous version.

**Comment by dillbyrne** [comment] 2015-05-05 21:08
Ok I'm going to try it on ubuntu 14.04 with firefox 31.6.0 esr with RAS 0.9.5.2 and 0.9.5.3

**Comment by dillbyrne** [comment] 2015-05-05 21:15
I have tried it in 2 different versions of RAS on 2 different operation systems with 2 different versions of firefox including your exact OS and browser combination and I can't reproduce your issues. 

It is something on your end. I'm closing this and the other issue as they are not reproducible and nobody else has reported them

**Closed by dillbyrne** 2015-05-05 21:15 UTC
Labels: not reproducible

**Comment by Jiriss** [comment] 2015-05-06 07:20
I can confirm that "Disable webRTC" parameter does not change when I created a new profile and test it. So network.websocket.enabled will change until after restart of the browser.

**Comment by dillbyrne** [comment] 2015-05-06 12:10
That is the wrong preference and it has been removed in later versions of firefox that the one you are currently using. The correct preference for webRTC is `media.peerconnection.enabled`
