### ISSUE TITLE
Spoof window size in addition to screen resolution

### ISSUE THREAD

**Issue by BLIGEL** [dillbyrne/random-agent-spoofer#427] opened 2016-06-25 12:14 UTC
One problem is that the add-on currently only spoofs the screen resolution which means your actual resolution can still be obtained if you keep your browser window at full size. This can also pose a problem if you spoof the screen resolution to a value lower than your real one so that the browser window is reported to be larger than the screen resolution.

**Comment by Arsouf** [comment] 2016-06-26 06:36
It spoof nothing for me, script injection are broken...

**Comment by bonbonboi** [comment] 2016-06-29 18:06
I confirm this issue as well, to me that feature is broken neither it work  in a full screen mode or in a restored screen, the issue is with iFrame contentWindow, so even you spoofed it with a Window property, some sites still could get yours by check your  iFrame contentWindow property.
Yes BLIGEL: it is not advised to use the maximized window while you are after privacy, that  what Tor browser is telling us about.
Meanwhile, you could use custom resolution for a specific web sites, on Firefox, press Ctrl+Shif+M, that time it forcibly going to spoof your actual window size, aka resolution...

**Comment by Arsouf** [comment] 2016-06-29 18:40
That's a pretty good tweak, but you know how to keep the specified resolution when you switch tab?

**Comment by bonbonboi** [comment] 2016-06-29 20:04
Screen Resolution is obtained by js (javascrip) if you are worrying about that, disable js when you visit a specific web site.

**Comment by Arsouf** [comment] 2016-06-29 20:12
I know but I'd like that even my whitelisted websites (javascript) don't detect my screen resolution, that's why I'm here

**Comment by bonbonboi** [comment] 2016-06-29 20:39
There is an add-on for Firefox going to help you with that, it's called NoScript.

**Comment by marzametal** [comment] 2016-07-05 05:18
Wasn't this part of the code revamp for script injection in the next release?

**Comment by dillbyrne** [comment] 2016-07-05 18:33
I'm still working on fixing it. I have screen spoofing fixed and it works in iframes now too. I have not found a solution to get the window spoofing but I'm sure it can be done. The old way I used to do it no longer works. I'm currently rewriting the whitelist handling code. It has to be done in two separate places (at the url request for headers and the point of script injection for canvas, etc) .

This will make it easier to transition to a GUI based whitelist instead of text as the text is not user friendly at all. I planned to do it sooner but the mozilla update broke tons of stuff so it is what it is. 

I'm going to close this as I plan to deal with it in #365 . 

My plan is to get the new whitelist code working and ship an update with new profiles. I will still need to fix the date/time options and window code as mentioned above so  the date option will most likly be greyed out in the next release.  

A new release is needed to fix a couple of issues the main ones being the broken script injection and the broken toggle mode. Also new profles are nice.

Sorry about the delay in this, I have been really busy and the initial version of the whitelist code did not work as intended so I had to look for another way.

**Closed by dillbyrne** 2016-07-05 18:33 UTC
