### ISSUE TITLE
Refresh loop

### ISSUE THREAD

**Issue by louipc** [dillbyrne/random-agent-spoofer#153] opened 2015-03-06 19:59 UTC
Using version 0.9.5.1 on firefox 36, I get sent into a refresh loop if I visit this page:
http://www.cbc.ca/m/news/alain-philippon-phone-password-case-powers-of-border-agents-and-police-differ-1.2983841

I have to disable the add-on via the firefox settings to stop the loop. Clicking [Disable RAS] checkbox does not stop it. Not sure if this appears in previous versions.

It may not enter the loop on the first page load, if not just manually refresh the page, and it should go in a refresh loop.

**Comment by dillbyrne** [comment] 2015-03-06 20:25
hello @louipc  I can confirm this. It has to do with the script injection which works on most sites but it seems to be causing a loop on this site. It seems the fact it is injected at all is causing problems.

The only thing I can do to prevent this is add an option to completely disable script injection. This will of course prevent screen and date spoofing, window name protection, spoofing of the vendor property and the whitelist from functioning while the script injection is disabled .

**Comment by louipc** [comment] 2015-03-06 20:49
On Fri 06 Mar 2015 12:25 -0800, dillbyrne wrote:
> hello @louipc  I can confirm this. It has to do with the script injection
> which works on most sites but it seems to be causing a loop on this site. It
> seems the fact it is injected at all is causing problems.
> 
> The only thing I can do to prevent this is add an option to completely
> disable script injection. This will of course prevent screen and date
> spoofing, window name protection, spoofing of the vendor property and the
> whitelist from functioning while the script injection is disabled .

Would it work to disable script injection, load the site, then enable?
I think that is a resonable solution for now. Thanks.

**Comment by dillbyrne** [comment] 2015-03-06 21:18
@louipc I have fund the cause it was not script injection as I first thought. it is a combination of the pref "network.http.use-cache" set to false for a fix to #121  and the disable dom storage option.

0.9.5.2 will have an option to disable network.http.use-cache in the extras but it will be set to enabled by default and it will have a "(recommended)" notice beside the  preference.

**Comment by louipc** [comment] 2015-03-06 22:09
On Fri 06 Mar 2015 13:18 -0800, dillbyrne wrote:
> @louipc I have fund the cause it was not script injection as I first thought.
> it is a combination of the pref "network.http.use-cache" set to false for a
> fix to #121  and the disable dom storage option.
> 
> 0.9.5.2 will have an option to disable network.http.use-cache in the extras
> but it will be set to enabled by default and it will have a "(recommended)"
> notice beside the  preference.

Ok. Thanks for your help.

**Comment by dillbyrne** [comment] 2015-03-06 22:12
@louipc You're welcome. I'm going to close this issue now as I have the GUI entry for the network cache in the master branch already from my last commit. I will try to have 0.9.5.2 released soon.

**Closed by dillbyrne** 2015-03-06 22:12 UTC
