### ISSUE TITLE
Spoof Via don't work

### ISSUE THREAD

**Issue by Otherz** [dillbyrne/random-agent-spoofer#263] opened 2015-07-13 06:55 UTC
Hello,
I just found your addon and it is really nice.
I already tested a few options and by doing this I recognized, that "Spoof Via" isn't working for me.

If I visit this link:
http://www.proxy-listen.de/Proxy/Proxychecker.html

There is always shown, that the via header doesn't exist.

btw. why is it not possible to edit these settings under options in your addon?:
- Spoof Accept
- Spoof Accepted-Encoding
- Spoof Accepted-Language (US English)

I mean, you can enable and disable the options, but why could you not set other values there?

Thanks.

**Comment by dillbyrne** [comment] 2015-07-17 14:33
The Via header works for me on that site. See attached screenshots

![t](https://cloud.githubusercontent.com/assets/2903711/8749309/b28fdb04-2c98-11e5-8765-796b116a879b.png)

![t2](https://cloud.githubusercontent.com/assets/2903711/8749399/37b02d48-2c99-11e5-9304-74ff93b77d17.png)


Can you clarify what exactly you mean by isn't working ?

 


It is not possible to change the accept headers because they are tailored to the current [profile](https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json). 

The reason you can choose to disable them was there from when the feature was first added.  Since the profiles initially only had  en-US language support I offered the option to disable the headers for non english speaking users who did not want sites showing english over the native language. This was accompanied by a warning in the addon description that disabling those headers would make you stand out.

With the next release RAS will have support for a selection of multiple language headers. Mainly firefox based profiles for now until users submit the default for chrome and IE in their respective regions, but the support is there.

**Comment by dillbyrne** [comment] 2015-08-11 21:45
Closing as it is not reproducible and there has been no reply.

**Closed by dillbyrne** 2015-08-11 21:45 UTC
Labels: not reproducible
