### ISSUE TITLE
after update to iceweasel 40 RAS icon to big

### ISSUE THREAD

**Issue by ZaphodBeeblebroks** [dillbyrne/random-agent-spoofer#278] opened 2015-08-12 19:11 UTC
RAS verson 0.9.5.3
After updating to Iceweasel 40 the RAS icon is 3 times to big for the addonbar or menubar. (I'm using the Noia Fox theme and Classic Theme restorer).
Icon was o.k. with Iceweasel (Firefox) 39.
![Uploading iceweasel4o_RASicon2.png…]()
![Uploading iceweasel40_RASicon.png…]()

**Comment by dillbyrne** [comment] 2015-08-12 23:03
Hello @ZaphodBeeblebroks  It works fine on iceweasel 40 here as you can see in my screen shot below . Can you fix your screenshots please ?.  

![t](https://cloud.githubusercontent.com/assets/2903711/9238929/905e7c3c-414e-11e5-924b-d871bb935ad9.png)


Try it in a fresh profile, see https://github.com/dillbyrne/random-agent-spoofer/wiki/Bug-reporting-guide

**Comment by ZaphodBeeblebroks** [comment] 2015-08-13 21:40
Hello Dillbyrne

    In a new profile it works, but that is no surprise. (I have always
    more than one profile, and always start Iceweasel with the profile
    manager.l



    I use a very old profile with a lot of addons (41), and rebuilding
    that profile is to much work, and fails 95%, with a CPU running 100%

    Everything was o.k. with the RAS icon until the update to Iceweasel 40.

    These are the screenshots:

    Icon in Menu


    Icon on addon bar




    I like your addon very much, but for the moment i have to switch
    back to the secret agent addon
    <https://www.dephormation.org.uk/?page=81>, until the RAS icon is
    returning to normal.

    I will check once in a while.

    This is the first time ever i send in a bug report to someone, I'm
    not used to it, sorry for that.


    Thanks for your quick reaction, all the best,






    Gerard Willems,
    Brielle,
    The Netherlands.

**Comment by timbo-lino** [comment] 2015-08-14 06:43
Hi, 

I can confirm this bug:
RAS 0.9.5.3
Firefox 40

It is okay on the Default Theme. But as soon as I active FTDeepDark (https://addons.mozilla.org/en-us/firefox/addon/ft-deepdark/) I get this big icon. All other icons are still small.

**Comment by timbo-lino** [comment] 2015-08-14 06:45
Okay, it seemed to be a problem with the theme. With the new beta19 Theme everything is okay.
Thanks for the great work!

**Comment by dillbyrne** [comment] 2015-08-25 15:12
@timbo-lino Thanks , glad you figured out the issue.

@ZaphodBeeblebroks 

There are no images attached in your post, if you are having trouble using the github image uploader then try https://imgur.com . 

Nothing has changed in that RAS version between the update and if it works in a profile on its own then the logical conclusion is that one of your other addons is interfering with it.

Do you have any addons that change the firefox theme such as CTR or similar ? Perhaps they could be causing the issue ?

RAS is using standard SDK code for the icon so it should not cause problems.

**Comment by fflintstone** [comment] 2015-11-12 02:51
I reported on the exact same issue in Firefox with the LavaFox theme.  Again, if you use the default theme, the icon looks normal, but it blows up to a much larger size in LavaFox.  Of course, it's easy to blame it on the theme, but since no other icons do the same thing in that same theme, then it seems other issues may be to blame.

**Comment by dillbyrne** [comment] 2016-01-02 18:45
@fflintstone RAS uses the generic jetpack SDK way of displaying an icon, there is simply no other way offered to do it so there is nothing I could change on my end. On the other hand the theme is styling the area where the icon resides and that is causing the issue. If I believed RAS to be at fault I would have no issue in admitting it but I'm making an educated guess when I say I suspect that the theme is using XUL to theme the browser and  it has an issue with handling SDK based addons.

I'm closing this as it works with the standard theme and therefore not a RAS issue .

**Closed by dillbyrne** 2016-01-02 18:45 UTC
Labels: not reproducible
