### ISSUE TITLE
Spoof Accept-Language and Time Zone spoofing not working

### ISSUE THREAD

**Issue by lesterslibby** [dillbyrne/random-agent-spoofer#398] opened 2016-04-14 08:01 UTC
The version number of RAS: 0.9.5.5, It was installed from Portable firefox add-on directory
   
 How you installed it: Fresh install
    
Your operating system and version: Windows 7 Home Basic 64bits service pack1 on a Vmware machine 
    
Your version of firefox: Firefox portable 
    
The addons you have installed: Click & clean, Flashlight, Foxyproxy, HTTPS everywhere, Lastpass, Modify Headers, No Javascript add-on, Random agent spoofer
    
Steps to reproduce your issue: When I  change accept language and timezone on RAS, I go to whoer.net, but language is the same and timezone is the same

**Comment by dillbyrne** [comment] 2016-04-16 10:57
@lesterslibby Thanks for your bug report this is a duplicate of #365  which is the cause of this issue. I am still trying to get an alternative working solution.

**Closed by dillbyrne** 2016-04-16 10:57 UTC
Labels: duplicate
