### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by PatSpiegel** [dillbyrne/random-agent-spoofer#303] opened 2015-10-10 10:02 UTC
Maybe it should be added random of a canvas, than its full blocking. Such as here https://github.com/kkapsner/CanvasBlocker/blob/master/lib/modifiedAPI.js

**Comment by RoxKilly** [comment] 2015-10-11 02:07
Agreed. This has been discussed and is on the developer's to-do list. See #111

**Comment by ron-gh** [comment] 2015-12-26 21:50
I don't think it's a good idea to use a random canvas footprint, because that will just make you more unique, which is exactly what you don't want.

**Comment by RoxKilly** [comment] 2015-12-26 23:04
@ron-gh , I guess it depends on "what exactly you don't want".  The way it would work, a new random footprint would be generated every time.  This defeats tracking because the tracker will be unable to recognize you the next time you visit the site.  Think about it this way; if our physical fingerprints changed every minute, it would be really difficult for a system to track us by recording the fingerprint of everyone who enters or leaves.  Good tracking requires not only a unique, but also a consistent fingerprint.

**Comment by ron-gh** [comment] 2015-12-27 11:50
I agree: It would be difficult to track you if you focus only on the canvas fingerprinting and you set a random value every time, but if you look at it from a higher perspective (by combining different properties from your fingerprint), then setting a random canvas is also a property of your fingerprint. IMO it's best to "go with the crowd" and have the most common value for canvas "Not supported"

**Comment by dillbyrne** [comment] 2015-12-30 02:30
When improving the canvas there would be an option to spoof and to block it and the user will be able to choose.

**Comment by dillbyrne** [comment] 2015-12-30 02:32
I'm closing this as it is a duplicate of #111

**Closed by dillbyrne** 2015-12-30 02:32 UTC
Labels: duplicate
