### ISSUE TITLE
Disable geolocation issue

### ISSUE THREAD

**Issue by sbs4000** [dillbyrne/random-agent-spoofer#120] opened 2015-01-12 11:26 UTC
Hello,

when the Disable Geolocation option is not used, the geo.enabled firefox parameter is set to true by Agent Spoofer when it is disabled. The correct behavior should be not to manage the parameter at all. The issue is that I would like to set geo.enabled on false always, regardless whether Agent Spoofer is active or not. But when I set it to false, Agent Spoofer reverts it to true even if this option is unchecked.

This is probably true for other parameters as well.

Best,
sbs4000

**Comment by dillbyrne** [comment] 2015-01-13 21:09
Hello @sbs4000 

The way RAS handles preferences is like that by design. As the addon can cause problems with some sites I wanted to have the option to quickly be able to completely disable or enable the addon . This means not only profile spoofing but also the headers and extras too. This meant reverting all the changes done by the addon In order to revert to a working state which I could be guaranteed to work. I chose the default values to revert to as they are known to work across all instances of firefox. 

If this option was not present then users would have to untick every option if something was not working until they found the cause of the issue.

The problem is that users use the toggle feature and think it is for spoofing profiles only, there is a specific default option for the profiles to disable profile spoofing while keeping the extras.

I am planning on removing the full toggle functionality and making the toggle option toggle between default profile and the last selected profile instead as this seems to be what most users expect of it. The extras in this case will have to be manually toggled on or off by users themselves. 

It will reduce a lot of code and make the addon less confusing for users, the fault for which lies with myself . If they still want to disable the addon they can do so using the addons manager. 

This will have the desired effect and give me some peace :smile_cat:  

This is a duplicate of  #27 so I am going to close this issue and I will update #27 when I make changes to RAS to remove the current toggle system in place. 

I will try to add it for 0.9.5.2

**Closed by dillbyrne** 2015-01-13 21:09 UTC
Labels: duplicate

**Comment by sbs4000** [comment] 2015-01-15 18:25
Hello dillbyrne,

thanks a lot for your fast and useful answer.
