### ISSUE TITLE
Preferences/Setting Reset when Add-on is Disable and Re-enable

### ISSUE THREAD

**Issue by ldgbc** [dillbyrne/random-agent-spoofer#127] opened 2015-01-19 03:42 UTC
Recently I have to temporarily display RAS in Add-on Manager, upon re-enable RAS all my setting is removed and is restore to the default setting.

Can you (@dillbyrne) make it so setting isn't remove when you add-on is disable?

**Comment by dillbyrne** [comment] 2015-01-20 13:01
@ldgbc this was done due to a bug in the FF SDK. When the bug is fixed I will change the behaviour of disable.

from https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Listening_for_load_and_unload

>Due to bug [627432](https://bugzilla.mozilla.org/show_bug.cgi?id=627432), your onUnload listener will never be called with uninstall: it will only be called with disable. See in particular [comment 12](https://bugzilla.mozilla.org/show_bug.cgi?id=627432#c12) on that bug.

**Comment by dillbyrne** [comment] 2015-08-11 21:28
I'm going to re add the toggle system into RAS in #272  and the firefox addon disable/enable system will make use of those methods.

**Comment by dillbyrne** [comment] 2015-11-26 20:14
duplicate of #272

**Closed by dillbyrne** 2015-11-26 20:14 UTC
Labels: duplicate
